# Reinforcement Learning Configuration
# Inherits from base_config.yaml and overrides specific settings for RL training

# RL Training settings
training:
  batch_size: 4
  gradient_accumulation_steps: 8
  learning_rate: 1e-6
  num_epochs: 10

# PPO specific configuration
rl:
  enabled: true
  algorithm: "ppo"
  ppo_epochs: 4
  mini_batch_size: 2
  clip_range: 0.2
  clip_range_vf: null
  vf_coef: 0.1
  ent_coef: 0.01
  max_grad_norm: 0.5
  target_kl: 0.1
  gamma: 0.99
  gae_lambda: 0.95

# Curriculum learning settings for RL
curriculum:
  enabled: true
  update_frequency: 100  # Update difficulty every N steps
  performance_threshold: 0.7
  difficulty_adaptation_rate: 0.05

# Length-aware reward settings
reward:
  enabled: true
  length_penalty_weight: 0.2
  target_length: 100
  length_penalty_type: "linear"  # or "exponential"
  correctness_bonus: 1.0
  partial_credit: true

# RL-specific evaluation
evaluation:
  eval_frequency: 500
  num_eval_episodes: 100
  save_best_reward_model: true
